name: cider
version: 0.0.2+1
description: Tools for Dart package maintainers. Automates CHANGLELOG and pubspec.yaml updates.
homepage: "https://github.com/f3ath/cider"

dependencies:
  args: ^1.6.0
  change: ^0.1.0
  intl: ^0.16.1
  markdown: ^2.1.5
  marker: ^0.1.0
  maybe_just_nothing: ^0.3.0
  pub_semver: ^1.4.4
  pubspec_yaml: ^2.0.1
  version_manipulation: ^0.0.2
  yaml: ^2.2.1

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.9.0

environment:
  sdk: ">=2.8.0 <3.0.0"

executables:
  cider: cider
